# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27167e51c136dfc1cb046bb105bb49fdce85aef7aac8584a221135c6dbe0b1362509ad59e729a2ce603dbdad8d99201c409b8f8904f1486c6e08c100009dbb7c

test:
  secret_key_base: 07065373d24f02a3e29f38cce9ebbb3adf0540e5b5761a88335b1292909f4bed12d2c32a2940c272d1fe979029b1e465d4b55c372221aba46b97ecf92593ead5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
